---
title: "Sick-Sicker Replication"
author: 
  - name: "John Graves"
    affiliation: 
      - "Vanderbilt University School of Medicine"
      - "Vanderbilt Owen Gradute School of Management"
      - "Vanderbilt University Medical Center"
    email: "john.graves@vanderbilt.edu"
  - name: "Shawn Garbett"
    affiliation: 
      - "Vanderbilt University School of Medicine"
      - "Vanderbilt University Medical Center"    
    email: "shawn.garbett@vumc.org"
  - name: "Kun-Woo Kim"
    affiliation:
      - "Vanderbilt University"
date: today
format: 
  closeread-html:
    css: des-styling.css
    code-tools: false
    fig-format: svg
    toc: false
    linkcolor: tomato
bibliography: references.bib    
editor_options: 
  chunk_output_type: console
---

# Setup

```{r}
library(tidyverse)
library(simmer)
library(here)
library(flextable)
source(here('discount.R'))
source(here('main_loop.R'))  # Boilerplate code
source(here('cea-table-functions.R'))
```

# Define Parameters

```{r}
inputs <- list(
    N      = 1e3,
    
    lambda.wait = 1/30,
    n.capacity = 1e7,
  
    # Parameters
    horizon=    75,      # Time horizon
    
    # Cycle => 1 year
    d.r    =     0.0,   # Discount Rate
    
    r.HS1  =     0.15,   # Disease Onset Rate / year       (H  -> S1)
    r.S1H  =     0.5,    # Recovery Rate / year            (S1 -> H)
    r.S1S2 =     0.105,   # Disease Progression rate / year (S1 -> S2)
    r.HD   =     0.002,  # Healthy to Dead rate / year     (H  -> D)
    hr.S1D =     3,      # Hazard ratio in S1 vs healthy 
    hr.S2D =    10,      # Hazard ratio in S2 vs healthy
    hr.S1S2.TrtB = 0.6,  # REduction in rate of disease progression
 
    # Annual Costs
    c.H    =  2000,      # Healthy individuals 
    c.S1   =  4000,      # Sick individuals in S1
    c.S2   = 15000,      # Sick individuals in S2
    c.D    =     0,      # Dead individuals
    c.TrtA  = 12000,     # Additional Annual cost for S1 and S2
    c.TrtB = 13000,      # Cost of treatment B
    
    # Utility Weights
    u.H    =     1.00,   # Healthy
    u.S1   =     0.75,   # S1
    u.S2   =     0.50,   # S2
    u.D    =     0.00,   # Dead
    
    # Intervention Effect
    u.TrtA  =     0.95,   # S1 Utility for treatment in S1
    
    wtp    =     1e5,    # 100k willingness to pay
    
    treatA = FALSE,
    treatB = FALSE
  )

counters <- c(
  "time_in_model",
  "death",
  "healthy",
  "sick1",
  "sick2",
  #"A", #This no longer is included here because we inlcude it in add_resource("A", inputs$n.capacity in the des_run function)
  "B"
)

# Define starting state of patient
initialize_patient <- function(traj, inputs)
{
  traj                   |>
  seize("time_in_model") |>
  set_attribute("AgeInitial", function() 25) |>
  set_attribute("State", 0) |> # Patients start healthy
  seize("healthy")       |>
  set_attribute("trtA", function() inputs$treatA == TRUE) |>
  set_attribute("trtB", function() inputs$treatB == TRUE)
}

# Cleanup function if a termination occurs
# Good for releasing any seized resources based on state.
cleanup_on_termination <- function(traj, inputs)
{
  traj |> 
  release("time_in_model") |>
  branch( 
    function() get_attribute(env, "State")+1,
      continue = rep(TRUE, 3),
      trajectory() |> release("healthy"),
      trajectory() |> release("sick1"),
      trajectory() |> release("sick2") 
  ) |>
  branch( # Assigned to treatment A and not healthy
    function() (get_attribute(env, "trtA")  && 
                get_attribute(env, "State")) + 1,
    continue = rep(TRUE, 2),
    trajectory(),  # No Treatment
    trajectory() |> release('A')
  ) |>
  branch( # Assigned to treatment B and not healthy
    function() (get_attribute(env, "trtB")  && 
                get_attribute(env, "State")) + 1,
    continue = rep(TRUE, 2),
    trajectory(),  # No Treatment
    trajectory() |> release('B')
  )
}


# terminate_simulation <- function(traj, inputs)
# {
#   traj |>
#   branch( function() 1, 
#           continue=FALSE,
#           trajectory() |> send("timeout.event") |> cleanup_on_termination(inputs)
#         )
# }

terminate_simulation <- function(inputs) {
  trajectory("Terminate") |>
    send("timeout.event") |>
    release("time_in_model") |>
    branch(
      function() get_attribute(env, "State") + 1,
      continue = rep(TRUE, 3),
      trajectory() |> release("healthy"),
      trajectory() |> release("sick1"),
      trajectory() |> release("sick2")
    ) |>
    branch(
      function() (get_attribute(env, "trtA") && get_attribute(env, "State")) + 1,
      continue = rep(TRUE, 2),
      trajectory(),
      trajectory() |> release("A")
    ) |>
    branch(
      function() (get_attribute(env, "trtB") && get_attribute(env, "State")) + 1,
      continue = rep(TRUE, 2),
      trajectory(),
      trajectory() |> release("B")
    )
}
years_till_death <- function(inputs)
{
  state <- get_attribute(env, "State")
  rate <- inputs$r.HD
  if(state == 1) rate <- rate * inputs$hr.S1D # Deal with Sick1 Hazard Ratio
  if(state == 2) rate <- rate * inputs$hr.S2D
  rexp(1, rate)
}

death <- function(traj, inputs) {
  death_cleanup <- terminate_simulation(trajectory("cleanup"), inputs)
  
  traj |> branch(
    function() 1,
    continue = c(FALSE),
    trajectory("Death") |>
      send("death.event") |>
      mark("death") |>
      join(death_cleanup)
  )
}

years_till_sick1 <- function(inputs)
{
  state <- get_attribute(env, "State") 
  if(state == 0) # 0 => Healthy
  {
    rexp(1,inputs$r.HS1)
  } else
  {
    inputs$horizon+1 # Past end of simulation time
  }
}

sick1 <- function(traj, inputs)
{
  traj                      |> 
  set_attribute("State", 1) |> # 1 => Sick 1 (S1)
  release('healthy')        |> # Track state change for tally later
  seize('sick1')            |>
  branch( 
    function() get_attribute(env, "trtA")+1,
    continue = rep(TRUE, 2),
    trajectory(),  # No Treatment
    trajectory() |> timeout(0) |> seize('A')
  )                         |>
  branch( 
    function() get_attribute(env, "trtB")+1,
    continue = rep(TRUE, 2),
    trajectory(),  # No Treatment
    trajectory() |> seize('B')
  )
}

sick1 <- function(traj, inputs)
{
  traj |> 
    set_attribute("State", 1) |>     # Enter Sick1
    release("healthy") |>            # Leave Healthy
    seize("sick1") |>                # Enter Sick1 pool

    # Treatment A: wait for access, but can be interrupted
    branch(
      function() get_attribute(env, "trtA") + 1,
      continue = rep(TRUE, 2),

      # No treatment A
      trajectory(),

      # Treatment A with potential interruption
      trajectory() |>
        trap("death.event", handler = terminate_simulation(inputs)) |>
        trap("timeout.event", handler = terminate_simulation(inputs)) |>

        renege_if("death", trajectory()) |>
        renege_if("timeout", trajectory()) |>

        seize("A") |>                      # Wait for and seize A
        timeout(1) |>                      # Duration of treatment
        release("A") |>                    # Release A if completed

        untrap("death.event") |>
        untrap("timeout.event")
    ) |>

    # Treatment B: seize if assigned, no renege logic added here
    branch(
      function() get_attribute(env, "trtB") + 1,
      continue = rep(TRUE, 2),
      trajectory(),
      trajectory() |> seize("B")
    )
}



years_till_healthy <- function(inputs)
{
  state <- get_attribute(env, "State") 
  if(state == 1) # 1 => Sick 1
  {
    rexp(1,inputs$r.S1H)
  } else
  {
    inputs$horizon+1 # Past end of simulation time
  }
}

healthy <- function(traj, inputs)
{
  traj                      |> 
  set_attribute("State", 0) |> # 0 => Healthy (H)
  seize('healthy')          |>
  release('sick1')          |>
  branch(
    function() get_attribute(env, "trtA") +1,
    continue = rep(TRUE, 2),
    trajectory(),  # No Treatment
    trajectory() |> release('A')
  )                         |>
  branch(
    function() get_attribute(env, "trtB") +1,
    continue = rep(TRUE, 2),
    trajectory(),  # No Treatment
    trajectory() |> release('B')
  )
}

years_till_sick2 <- function(inputs)
{
  state <- get_attribute(env, "State") 
  onB <- get_attribute(env, "trtB")
  
  if(state == 1 && !(onB)) # 1 => Sick1
  {
    rexp(1,inputs$r.S1S2)
  } else if (state == 1 && onB) 
  {
    rexp(1,inputs$r.S1S2 * inputs$hr.S1S2.TrtB)
  } else
  {
    inputs$horizon+1 # Past end of simulation time
  }
}

sick2 <- function(traj, inputs)
{
  traj                      |> 
  set_attribute("State", 2) |> # 2 => Sick 2 (S2)
  release('sick1')          |> # Track state change for tally later
  seize('sick2')
}

# Main Event registry
event_registry <- list(
  list(name = "Death",
     attr = "aDeath",
     time_to_event = years_till_death,
     func = death,
     reactive = TRUE),
     
  list(name = "Terminate at time horizon",
     attr = "aTerminate",
     time_to_event = function(inputs) inputs$horizon - now(env),
     func = terminate_simulation,
     reactive = FALSE),

  # list(name          = "Terminate at time horizon",
  #      attr          = "aTerminate",
  #      time_to_event = function(inputs) inputs$horizon-now(env),
  #      func          = terminate_simulation,
  #      reactive      = FALSE),
  # list(name          = "Death",
  #      attr          = "aDeath",
  #      time_to_event = years_till_death,
  #      func          = death,
  #      reactive      = TRUE),
  list(name          = "Sick1",
       attr          = "aSick1",
       time_to_event = years_till_sick1,
       func          = sick1,
       reactive      = TRUE),
  list(name          = "Healthy",
       attr          = "aHealthy",
       time_to_event = years_till_healthy,
       func          = healthy,
       reactive      = TRUE),
  list(name          = "Sick2",
       attr          = "aSick2",
       time_to_event = years_till_sick2,
       func          = sick2,
       reactive      = TRUE)
)

cost_arrivals <- function(arrivals, inputs)
{
  arrivals$cost  <- 0  # No costs yet
  arrivals$dcost <- 0  # No discounted costs either
  
  selector = arrivals$resource == 'healthy'
  arrivals$cost[selector] <- inputs$c.H *
    (arrivals$end_time[selector] - arrivals$start_time[selector])
  arrivals$dcost[selector] <- discount_value(inputs$c.H,
    arrivals$start_time[selector], arrivals$end_time[selector])
  
  selector = arrivals$resource == 'sick1'
  arrivals$cost[selector] <- inputs$c.S1 *
    (arrivals$end_time[selector] - arrivals$start_time[selector])
  arrivals$dcost[selector] <- discount_value(inputs$c.S1,
    arrivals$start_time[selector], arrivals$end_time[selector])
  
  selector = arrivals$resource == 'sick2'
  arrivals$cost[selector] <- inputs$c.S2 *
    (arrivals$end_time[selector] - arrivals$start_time[selector])
  arrivals$dcost[selector] <- discount_value(inputs$c.S2,
    arrivals$start_time[selector], arrivals$end_time[selector])
 
  selector = arrivals$resource == 'A'
  arrivals$cost[selector] <- inputs$c.TrtA *
    (arrivals$end_time[selector] - arrivals$start_time[selector])
  arrivals$dcost[selector] <- discount_value(inputs$c.TrtA,
    arrivals$start_time[selector], arrivals$end_time[selector])
  
  selector = arrivals$resource == 'B'
  arrivals$cost[selector] <- inputs$c.TrtB *
    (arrivals$end_time[selector] - arrivals$start_time[selector])
  arrivals$dcost[selector] <- discount_value(inputs$c.TrtB,
    arrivals$start_time[selector], arrivals$end_time[selector])
 
  arrivals
}

qaly_arrivals <- function(arrivals, inputs)
{
  arrivals$qaly  <- 0  # No qaly yet
  arrivals$dqaly <- 0  # No discounted qaly either
  
  selector <- arrivals$resource == 'healthy'
  arrivals$qaly[selector] <-
    inputs$u.H*
     (arrivals$end_time[selector] - arrivals$start_time[selector])
  arrivals$dqaly[selector] <- 
      discount_value(inputs$u.H, 
                     arrivals$start_time[selector],
                     arrivals$end_time[selector])
  
  selector <- arrivals$resource == 'sick1'
  uS1 <- if(inputs$treatA) inputs$u.TrtA else inputs$u.S1
  arrivals$qaly[selector] <-
    uS1*
     (arrivals$end_time[selector] - arrivals$start_time[selector])
  arrivals$dqaly[selector] <- 
      discount_value(uS1, 
                     arrivals$start_time[selector],
                     arrivals$end_time[selector])
  
  selector <- arrivals$resource == 'sick2'
  arrivals$qaly[selector] <-
    inputs$u.S2*
     (arrivals$end_time[selector] - arrivals$start_time[selector])
  arrivals$dqaly[selector] <- 
      discount_value(inputs$u.S2, 
                     arrivals$start_time[selector],
                     arrivals$end_time[selector])
  
  arrivals
}

# This does a single DES run versus the defined inputs.
des_run <- function(inputs)
{
  env  <<- simmer("SickSicker")
  traj <- des(env, inputs)
  env |> 
    create_counters(counters) |>
    add_resource("A", inputs$n.capacity) |> 
    add_generator("patient", traj, at(rep(0, inputs$N)), mon=2) |>
    run(inputs$horizon+1/365) |> # Simulate just past horizon (in years)
    wrap()
        
  get_mon_arrivals(env, per_resource = T) |>
    cost_arrivals(inputs) |> 
    qaly_arrivals(inputs) 
}

aggregate_run <- function(run) {
  run |>
  as_tibble()  |> 
  group_by(name) |> 
  summarise_at(vars(dcost,dqaly),sum) |> 
  ungroup() |> 
  summarise_at(vars(dcost,dqaly),mean)
}

```

```{r}
# seed 123 and N=1e4 gets quite close to embedded results

# Standard of Care (no treatments)
set.seed(123)
run.SoC <- des_run(modifyList(inputs, list(treatA = FALSE, treatB = FALSE)))
result.SoC <- run.SoC |> aggregate_run() |> mutate(strategy = "SoC")
run.SoC %>% as_tibble() %>% filter(name == "patient1") %>% mutate(foo = !as.integer(resource == "time_in_model")) %>% arrange(foo,start_time,end_time) %>% dplyr::select(-foo)
  
#- Treatment A - Unconstrained
set.seed(123)
run.A.unconstrained <- des_run(modifyList(inputs, list(treatA = TRUE, treatB = FALSE, n.capacity=1e6)))
result.A.unconstrained <- run.A.unconstrained |> aggregate_run() |> mutate(strategy = "A.unconstrained")
run.A.unconstrained %>% as_tibble() %>% filter(name == "patient1") %>% mutate(foo = !as.integer(resource == "time_in_model")) %>% arrange(foo,start_time,end_time) %>% dplyr::select(-foo)
  
#- Treatment A - Fully Constrained (should be same as B alone)
set.seed(123)
run.A.fullyconstrained <- des_run(modifyList(inputs, list(treatA = TRUE, treatB = FALSE, n.capacity=100)))
result.A.fullyconstrained <- run.A.fullyconstrained |> aggregate_run() |> mutate(strategy = "A.fullyconstrained")

result.SoC
result.A.unconstrained
result.A.fullyconstrained

```

```{r}

```

